### PR TITLE
Submitting my app for review

### PR DESCRIPTION
**Pull request by Lpaydat**
This PR introduces a new decentralized application (dApp) built using the Linera SDK. The dApp is a blockchain-based implementation of the popular game 2048, designed with Svelte for the frontend. The app leverages Linera's decentralized architecture to provide a seamless and scalable user experience.

**Key Features:**
Frontend: Built with Svelte for fast, responsive gameplay and a modern user interface.
Blockchain Integration: The game state and user interactions are recorded on the blockchain, utilizing Linera SDK’s devnet for development.
Smart Contracts: Game logic is managed through smart contracts, ensuring transparency and immutability of the game’s rules and results.
Future Enhancements: The app is designed to be easily extendable with potential features like leaderboards, rewards, or NFTs for top scores.

**Purpose**
The goal of this project is to showcase how traditional games can be transformed into decentralized applications using Linera SDK, taking advantage of blockchain for trustless interactions and a more robust backend.

### CODE REVIEW

**Comment by Lpaydat** [comment]
init commit

**Comment by valkrav-76** [comment]
ok

**Comment by valkrav-76** [comment]
ok

**Review by Nyi-ui — APPROVED** [review]

**Review by Nyi-ui — APPROVED** [review]

**Comment by Telespallabobo** [comment]
ok

**Pull request merged**
